TrainingEventAttendanceSettingsScreen As screen:

    TEAttendSettings__localizer As Localizer_1:
        Localize: |-
            =/*
                @author: ryan@werkncode.net
                Usage: To use the localizer in your environment create a table with the following structure in the dataverse:
            
                LocalizationEnFr(
                        (String) StringId, (String) En, (String) Fr, (Boolean) Flagged
                )
            
                Then in your app, on the main/first screen create a custom component (called _localizer extending from Localizer here).
            
                To translate text use the following function call on the localizer component:
            
                _localizer.Localize("APP_SCREEN_STRING_ID", LangEn), this will return the English or the French Text
            */
            If(
                IsLangEn = true,
                //IF
                First(
                    Search(
                        LocalizationEnFr,
                        StringId,
                        "wywm_stringid"
                    )
                ).En,
                //ELSE
                First(
                    Search(
                        LocalizationEnFr,
                        StringId,
                        "wywm_stringid"
                    )
                ).Fr
            )
        Visible: =false
        ZIndex: =1

    TEAttendSettings__HamburgerIconPlaceholder_1 As icon.Add:
        Color: =RGBA(255, 255, 255, 1)
        Height: =60
        Icon: =Icon.Hamburger
        PaddingBottom: =5
        PaddingLeft: =10
        PaddingRight: =5
        PaddingTop: =10
        Width: =65
        X: =16
        Y: =15
        ZIndex: =3

    TEAttendSettings__EventContainer As groupContainer.manualLayoutContainer:
        Height: =1046
        Width: =Parent.Width
        Y: =90
        ZIndex: =4

        TEAttendSettings_ButtonContainer As groupContainer.verticalAutoLayoutContainer:
            Height: =96
            LayoutAlignItems: =LayoutAlignItems.Center
            LayoutJustifyContent: =LayoutJustifyContent.Center
            LayoutMode: =LayoutMode.Auto
            LayoutOverflowY: =LayoutOverflow.Scroll
            Width: =Parent.Width
            Y: =90
            ZIndex: =1

            TEAttendSettings_DetailsButton As button:
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =140
                OnSelect: =Navigate(TrainingEventAttendanceDetailsScreen, Fade);
                Size: =24
                Text: ="Details"
                ZIndex: =1

            TEAttendSettings_ObjButton As button:
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =140
                OnSelect: |-
                    =Navigate(
                        TrainingEventAttendanceObjectivesScreen, 
                        None
                    );
                Size: =20
                Text: ="Objectives"
                ZIndex: =2

            TEAttendSettings_DocButton As button:
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =140
                OnSelect: |-
                    =Navigate(
                        TrainingEventAttendanceDocumentsScreen, 
                        None
                    );
                Size: =20
                Text: ="Documents"
                ZIndex: =3

            TEAttendSettings_SettingsButton As button:
                Fill: =RGBA(166, 166, 166, 1)
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =140
                Size: =If(LangEn, 20, 19)
                Text: =If(LangEn, "Settings","Paramètres")
                ZIndex: =4

        TEAttendSettings_Container As groupContainer.verticalAutoLayoutContainer:
            Height: =626
            LayoutAlignItems: =LayoutAlignItems.Stretch
            LayoutDirection: =LayoutDirection.Vertical
            LayoutJustifyContent: =LayoutJustifyContent.Center
            LayoutMode: =LayoutMode.Auto
            Width: =640
            Y: =186
            ZIndex: =3

            TEAttendSettings_RemindLabel As label:
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =560
                Size: =21
                Text: ="Reminders"
                Width: =560
                ZIndex: =1

            TEAttendSettings_SendRemind As label:
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =560
                LineHeight: =2
                Size: =21
                Text: ="Send reminder emails."
                Width: =560
                ZIndex: =2

            TEAttendSettings_Rectangle As rectangle:
                BorderColor: =RGBA(255, 255, 255, 1)
                Fill: =RGBA(255, 255, 255, 1)
                Height: =20
                ZIndex: =3

            TEAttendSettings_RemindDatePicker As datepicker:
                DefaultDate: =DateAdd(AttendData.'Start Date',-3)
                DisplayMode: =DisplayMode.Disabled
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =500
                Size: =24
                Width: =450
                ZIndex: =4

            TEAttendSettings_CheckInLabel As label:
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =560
                Size: =21
                Text: ="Check-In Settings"
                Width: =560
                ZIndex: =5

            TEAttendSettings_OpensAtLabel As label:
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =560
                Size: =21
                Text: ="Check-in opens at"
                Width: =560
                ZIndex: =6

            TEAttendSettings_CheckInDatePicker As datepicker:
                DefaultDate: =AttendData.'Start Date'
                DisplayMode: =DisplayMode.Disabled
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =575
                Size: =24
                Width: =575
                ZIndex: =7

            TEAttendSettings_ClosesAtLabel As label:
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =560
                Size: =21
                Text: ="Check-in closes at"
                Width: =560
                ZIndex: =8

            TEAttendSettings_ClosesAtDatePicker As datepicker:
                DefaultDate: =AttendData.'End Date'
                DisplayMode: =DisplayMode.Disabled
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =575
                Size: =24
                Width: =575
                ZIndex: =9

        TEAttendSettings_HtmlText As htmlViewer:
            Height: =54
            HtmlText: ="<b><font color=blue>Change</font></b>"
            Size: =20
            Width: =131
            X: =509
            Y: =445
            ZIndex: =5

    TEAttendSettings_RemindToggle As toggleSwitch:
        Default: =true
        Height: =49
        Reset: =true
        Size: =21
        Width: =154
        X: =357
        Y: =381
        ZIndex: =6

    MainHeader_3 As MainHeader:
        ZIndex: =7

