TrainingEventAttendanceDocumentsScreen As screen:

    TEAttendDocs_localizer As Localizer_1:
        Localize: |-
            =/*
                @author: ryan@werkncode.net
                Usage: To use the localizer in your environment create a table with the following structure in the dataverse:
            
                LocalizationEnFr(
                        (String) StringId, (String) En, (String) Fr, (Boolean) Flagged
                )
            
                Then in your app, on the main/first screen create a custom component (called _localizer extending from Localizer here).
            
                To translate text use the following function call on the localizer component:
            
                _localizer.Localize("APP_SCREEN_STRING_ID", LangEn), this will return the English or the French Text
            */
            If(
                IsLangEn = true,
                //IF
                First(
                    Search(
                        LocalizationEnFr,
                        StringId,
                        "wywm_stringid"
                    )
                ).En,
                //ELSE
                First(
                    Search(
                        LocalizationEnFr,
                        StringId,
                        "wywm_stringid"
                    )
                ).Fr
            )
        Visible: =false
        ZIndex: =1

    TEAttendDocs_EventContainer_2 As groupContainer.manualLayoutContainer:
        Height: =1046
        Width: =Parent.Width
        Y: =90
        ZIndex: =4

        TEAttendDocs_ButtonContainer As groupContainer.verticalAutoLayoutContainer:
            Height: =96
            LayoutAlignItems: =LayoutAlignItems.Center
            LayoutJustifyContent: =LayoutJustifyContent.Center
            LayoutMode: =LayoutMode.Auto
            LayoutOverflowY: =LayoutOverflow.Scroll
            Width: =Parent.Width
            Y: =90
            ZIndex: =1

            TEAttendDocs_DetailsButton As button:
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =140
                OnSelect: =Navigate(TrainingEventAttendanceDetailsScreen, Fade);
                Size: =24
                Text: ="Details"
                ZIndex: =1

            TEAttendDocs_ObjButton As button:
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =140
                OnSelect: |-
                    =Navigate(
                        TrainingEventAttendanceObjectivesScreen, 
                        None
                    );
                Size: =20
                Text: ="Objectives"
                ZIndex: =2

            TEAttendDocs_DocButton As button:
                Fill: =RGBA(166, 166, 166, 1)
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =140
                Size: =20
                Text: ="Documents"
                ZIndex: =3

            TEAttendDocs_SettingsButton As button:
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =140
                OnSelect: |-
                    =Navigate(
                        TrainingEventAttendanceSettingsScreen, 
                        None
                    );
                Size: =If(LangEn, 20, 19)
                Text: =If(LangEn, "Settings","Paramètres")
                ZIndex: =4

        TEAttendDocs_Container As groupContainer.verticalAutoLayoutContainer:
            Height: =487
            LayoutAlignItems: =LayoutAlignItems.Stretch
            LayoutDirection: =LayoutDirection.Vertical
            LayoutJustifyContent: =LayoutJustifyContent.Center
            LayoutMode: =LayoutMode.Auto
            Width: =640
            Y: =186
            ZIndex: =3

            AttachContainer1 As groupContainer.horizontalAutoLayoutContainer:
                Height: =225
                LayoutAlignItems: =LayoutAlignItems.Center
                LayoutJustifyContent: =LayoutJustifyContent.Center
                LayoutMinHeight: =112
                LayoutMinWidth: =250
                LayoutMode: =LayoutMode.Auto
                Visible: |-
                    =If(IsBlank(AttendData.'Attachment #1'.FileName) = true, false, true)
                ZIndex: =4

                TEAttendDocs_Attach1Btn_1 As button:
                    Color: =RGBA(0, 0, 0, 1)
                    DisabledColor: =RGBA(0, 0, 0, 0)
                    Fill: =Transparent
                    FontWeight: =FontWeight.Normal
                    Height: =48
                    HoverBorderColor: =RGBA(0, 0, 0, 0)
                    HoverColor: =RGBA(0, 0, 0, 1)
                    HoverFill: =Transparent
                    LayoutMinHeight: =70
                    LayoutMinWidth: =280
                    OnSelect: |-
                        =If(
                            EndsWith(
                                Lower(AttendData.'Attachment #1'.FileName),
                                ".png"
                            ) || EndsWith(
                                Lower(AttendData.'Attachment #1'.FileName),
                                ".jpg"
                            ) || EndsWith(
                                Lower(AttendData.'Attachment #1'.FileName),
                                ".jpeg"
                            ),
                            Set(
                                showImg,
                                !showImg
                            );
                            Set(
                                showAttachmentCancel,
                                !showAttachmentCancel
                            );
                            ,
                            // pdf or docx (nested if)
                            If(
                                EndsWith(
                                    Lower(AttendData.'Attachment #1'.FileName),
                                    ".pdf"
                                ),
                                Set(
                                    showPdf,
                                    !showPdf
                                );
                                Set(
                                    showAttachmentCancel,
                                    !showAttachmentCancel
                                );
                                ,
                            // not an image && not a pdf
                                false
                            );
                            
                        )
                    PressedBorderColor: =
                    PressedColor: =
                    Size: =20
                    Text: |+
                        =//EventData.wywm_TrainingEvent.'Attachment #1'.Value
                        AttendData.'Attachment #1'.FileName
                        //EventData.wywm_TrainingEvent.wywm_attachment.FileName
                        
                    VerticalAlign: =VerticalAlign.Top
                    Visible: |
                        =true
                    Width: =469
                    X: =65
                    Y: =880
                    ZIndex: =1

                TEAttendDocs_Attach1Download_1 As icon.Save:
                    Color: =RGBA(56, 96, 178, 1)
                    Height: =30
                    Icon: =Icon.Download
                    OnSelect: |-
                        =
                        Download(BASE_ENVIRON_URL & "wywm_trainingevents("&AttendData.'Training Event'&")/wywm_attachment/$value");
                        Launch(BASE_ENVIRON_URL & "wywm_trainingevents("&AttendData.'Training Event'&")/wywm_attachment/$value");
                        // BASE_ENVIRON_URL wywm,_trainingEvents(unique_id)/attachment_column_name/$value
                        //dff3e810-0352-ec11-8f8e-000d3ae88643
                    Visible: |
                        =true
                    Width: =40
                    X: =407
                    Y: =6
                    ZIndex: =2

            AttachContainer2 As groupContainer.horizontalAutoLayoutContainer:
                Height: =225
                LayoutAlignItems: =LayoutAlignItems.Center
                LayoutJustifyContent: =LayoutJustifyContent.Center
                LayoutMinHeight: =112
                LayoutMinWidth: =250
                LayoutMode: =LayoutMode.Auto
                Visible: |-
                    =If(IsBlank(AttendData.'Attachment #3'.FileName) = true, false, true)
                ZIndex: =5

                TEAttendDocs_Attach1Btn_2 As button:
                    Color: =RGBA(0, 0, 0, 1)
                    DisabledColor: =RGBA(0, 0, 0, 0)
                    Fill: =Transparent
                    FontWeight: =FontWeight.Normal
                    Height: =48
                    HoverBorderColor: =RGBA(0, 0, 0, 0)
                    HoverColor: =RGBA(0, 0, 0, 1)
                    HoverFill: =Transparent
                    LayoutMinHeight: =70
                    LayoutMinWidth: =280
                    OnSelect: |-
                        =If(
                            EndsWith(
                                Lower(AttendData.'Attachment #2'.FileName),
                                ".png"
                            ) || EndsWith(
                                Lower(AttendData.'Attachment #2'.FileName),
                                ".jpg"
                            ) || EndsWith(
                                Lower(AttendData.'Attachment #2'.FileName),
                                ".jpeg"
                            ),
                            Set(
                                showImg,
                                !showImg
                            );
                            Set(
                                showAttachmentCancel,
                                !showAttachmentCancel
                            );
                            ,
                            // pdf or docx (nested if)
                            If(
                                EndsWith(
                                    Lower(AttendData.'Attachment #2'.FileName),
                                    ".pdf"
                                ),
                                Set(
                                    showPdf,
                                    !showPdf
                                );
                                Set(
                                    showAttachmentCancel,
                                    !showAttachmentCancel
                                );
                                ,
                            // not an image && not a pdf
                                false
                            );
                            
                        )
                    PressedBorderColor: =
                    PressedColor: =
                    Size: =20
                    Text: |+
                        =//EventData.wywm_TrainingEvent.'Attachment #1'.Value
                        AttendData.'Attachment #2'.FileName
                        //EventData.wywm_TrainingEvent.wywm_attachment.FileName
                        
                    VerticalAlign: =VerticalAlign.Top
                    Visible: |
                        =true
                    Width: =469
                    X: =65
                    Y: =874
                    ZIndex: =1

                TEAttendDocs_Attach1Download_2 As icon.Save:
                    Color: =RGBA(56, 96, 178, 1)
                    Height: =30
                    Icon: =Icon.Download
                    OnSelect: |-
                        =
                        Download(BASE_ENVIRON_URL & "wywm_trainingevents("&AttendData.'Training Event'&")/wywm_attachment/$value");
                        Launch(BASE_ENVIRON_URL & "wywm_trainingevents("&AttendData.'Training Event'&")/wywm_attachment/$value");
                        // BASE_ENVIRON_URL wywm,_trainingEvents(unique_id)/attachment_column_name/$value
                        //dff3e810-0352-ec11-8f8e-000d3ae88643
                    Visible: |
                        =true
                    Width: =40
                    X: =342
                    Y: =6
                    ZIndex: =2

            AttachContainer3 As groupContainer.horizontalAutoLayoutContainer:
                Height: =225
                LayoutAlignItems: =LayoutAlignItems.Center
                LayoutJustifyContent: =LayoutJustifyContent.Center
                LayoutMinHeight: =112
                LayoutMinWidth: =250
                LayoutMode: =LayoutMode.Auto
                Visible: |-
                    =If(IsBlank(AttendData.'Attachment #2'.FileName) = true, false, true)
                ZIndex: =6

                TEAttendDocs_Attach1Btn_3 As button:
                    Color: =RGBA(0, 0, 0, 1)
                    DisabledColor: =RGBA(0, 0, 0, 0)
                    Fill: =Transparent
                    FontWeight: =FontWeight.Normal
                    Height: =48
                    HoverBorderColor: =RGBA(0, 0, 0, 0)
                    HoverColor: =RGBA(0, 0, 0, 1)
                    HoverFill: =Transparent
                    LayoutMinHeight: =70
                    LayoutMinWidth: =280
                    OnSelect: |-
                        =If(
                            EndsWith(
                                Lower(AttendData.'Attachment #3'.FileName),
                                ".png"
                            ) || EndsWith(
                                Lower(AttendData.'Attachment #3'.FileName),
                                ".jpg"
                            ) || EndsWith(
                                Lower(AttendData.'Attachment #3'.FileName),
                                ".jpeg"
                            ),
                            Set(
                                showImg,
                                !showImg
                            );
                            Set(
                                showAttachmentCancel,
                                !showAttachmentCancel
                            );
                            ,
                            // pdf or docx (nested if)
                            If(
                                EndsWith(
                                    Lower(AttendData.'Attachment #3'.FileName),
                                    ".pdf"
                                ),
                                Set(
                                    showPdf,
                                    !showPdf
                                );
                                Set(
                                    showAttachmentCancel,
                                    !showAttachmentCancel
                                );
                                ,
                            // not an image && not a pdf
                                false
                            );
                            
                        )
                    PressedBorderColor: =
                    PressedColor: =
                    Size: =20
                    Text: |+
                        =//EventData.wywm_TrainingEvent.'Attachment #1'.Value
                        AttendData.'Attachment #2'.FileName
                        //EventData.wywm_TrainingEvent.wywm_attachment.FileName
                        
                    VerticalAlign: =VerticalAlign.Top
                    Visible: |
                        =true
                    Width: =469
                    X: =65
                    Y: =874
                    ZIndex: =1

                TEAttendDocs_Attach1Download_3 As icon.Save:
                    Color: =RGBA(56, 96, 178, 1)
                    Height: =30
                    Icon: =Icon.Download
                    OnSelect: |-
                        =
                        Download(BASE_ENVIRON_URL & "wywm_trainingevents("&AttendData.'Training Event'&")/wywm_attachment/$value");
                        Launch(BASE_ENVIRON_URL & "wywm_trainingevents("&AttendData.'Training Event'&")/wywm_attachment/$value");
                        // BASE_ENVIRON_URL wywm,_trainingEvents(unique_id)/attachment_column_name/$value
                        //dff3e810-0352-ec11-8f8e-000d3ae88643
                    Visible: |
                        =true
                    Width: =40
                    X: =342
                    Y: =6
                    ZIndex: =2

    MainHeader_4 As MainHeader:
        ZIndex: =7

