TrainingEventAttendanceDetailsScreen As screen:

    TEAttendDetails_localizer As Localizer_1:
        Localize: |-
            =/*
                @author: ryan@werkncode.net
                Usage: To use the localizer in your environment create a table with the following structure in the dataverse:
            
                LocalizationEnFr(
                        (String) StringId, (String) En, (String) Fr, (Boolean) Flagged
                )
            
                Then in your app, on the main/first screen create a custom component (called _localizer extending from Localizer here).
            
                To translate text use the following function call on the localizer component:
            
                _localizer.Localize("APP_SCREEN_STRING_ID", LangEn), this will return the English or the French Text
            */
            If(
                IsLangEn = true,
                //IF
                First(
                    Search(
                        LocalizationEnFr,
                        StringId,
                        "wywm_stringid"
                    )
                ).En,
                //ELSE
                First(
                    Search(
                        LocalizationEnFr,
                        StringId,
                        "wywm_stringid"
                    )
                ).Fr
            )
        Visible: =false
        ZIndex: =1

    TEAttendDetails__EventContainer As groupContainer.manualLayoutContainer:
        ChildTabPriority: =false
        EnableChildFocus: =false
        Height: =1046
        Width: =640
        Y: =90
        ZIndex: =4

        TEAttendDetails_ButtonContainer As groupContainer.verticalAutoLayoutContainer:
            Height: =96
            LayoutAlignItems: =LayoutAlignItems.Center
            LayoutJustifyContent: =LayoutJustifyContent.Center
            LayoutMode: =LayoutMode.Auto
            LayoutOverflowY: =LayoutOverflow.Scroll
            Width: =Parent.Width
            Y: =90
            ZIndex: =1

            TEAttendDetails_DetailsButton As button:
                Fill: =RGBA(166, 166, 166, 1)
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =140
                Size: =24
                Text: =If(LangEn, "Details", "Détails")
                ZIndex: =1

            TEAttendDetails_ObjButton As button:
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =140
                OnSelect: |-
                    =Navigate(
                        TrainingEventAttendanceObjectivesScreen, 
                        None
                    );
                Size: =20
                Text: =If(LangEn, "Objectives", "Objectifs")
                ZIndex: =2

            TEAttendDetails_DocButton As button:
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =140
                OnSelect: |-
                    =Navigate(
                        TrainingEventAttendanceDocumentsScreen, 
                        None
                    );
                Size: =20
                Text: ="Documents"
                ZIndex: =3

            TEAttendDetails_SettingsButton As button:
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =140
                OnSelect: |-
                    =Navigate(
                        TrainingEventAttendanceSettingsScreen, 
                        None
                    );
                Size: =If(LangEn, 20, 19)
                Text: =If(LangEn, "Settings","Paramètres")
                ZIndex: =4

        TEAttendDetails_Container3 As groupContainer.verticalAutoLayoutContainer:
            Height: =488
            LayoutAlignItems: =LayoutAlignItems.Stretch
            LayoutDirection: =LayoutDirection.Vertical
            LayoutMode: =LayoutMode.Auto
            Width: =610
            X: =15
            Y: =197
            ZIndex: =3

            TEAttendDetails_GroupIcon As icon.People:
                Height: =100
                Icon: =Icon.People
                LayoutMinWidth: =100
                ZIndex: =1

            TEAttendDetails_NumAcceptLabel As label:
                Align: =Align.Center
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =560
                Size: =21
                Text: |-
                    =With(
                        {
                            Attendees: Filter(
                                AttendData.'Training Event Attendees',
                                'Commit to Training Status' = [@'Commit to Training Status'].Accepted
                            )
                        },
                        CountRows(Attendees)
                    )
                     & If(LangEn, " Member(s) Accepted", " Membre(s) Accepté(es)")
                Width: =560
                ZIndex: =2

            TEAttendDetails_ConformButton As button:
                DisplayMode: =If(AttendData.'Start Date' > (Today()+7), DisplayMode.Disabled, DisplayMode.Edit)
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =280
                OnSelect: =Navigate(AttendanceConfirmationScreen,None);
                Size: =24
                Text: =If(LangEn, "Confirm Attendance", "Confirmer la Présence")
                Visible: |-
                    =//If(EventData.EventDate < Today(), false, true)
                    true
                Width: =500
                ZIndex: =3

            TEAttendDetails_Rectangle As rectangle:
                Fill: =RGBA(255, 255, 255, 1)
                Height: =25
                ZIndex: =5

            TEAttendDetails_OPILabel As label:
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =560
                Size: =30
                Text: ="OPI"
                Width: =560
                ZIndex: =6

            TEAttendDetails_OPIName As label:
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =560
                Size: =21
                Text: |-
                    =If(
                        LangEn,
                        LookUp(
                            Personnels,
                            Personnel = AttendOpiID
                        ).'Current Rank'.'Description Abbreviation Eng' & " " & LookUp(
                            Personnels,
                            Personnel = AttendOpiID
                        ).'Last Name' & ", " & LookUp(
                            Personnels,
                            Personnel = AttendOpiID
                        ).'First Name',
                        LookUp(
                            Personnels,
                            Personnel = AttendOpiID
                        ).'Current Rank'.'Description Abbreviation FR' & " " & LookUp(
                            Personnels,
                            Personnel = AttendOpiID
                        ).'Last Name' & ", " & LookUp(
                            Personnels,
                            Personnel = AttendOpiID
                        ).'First Name'
                    )
                Width: =560
                ZIndex: =7

            TEAttendDetails_DetailsLabel As label:
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =560
                Size: =30
                Text: =If(LangEn, "Details", "Détails")
                Width: =560
                ZIndex: =8

        TEAttendDetails_Container2 As groupContainer.horizontalAutoLayoutContainer:
            Height: =157
            LayoutMode: =LayoutMode.Auto
            LayoutWrap: =true
            Width: =610
            X: =15
            Y: =685
            ZIndex: =5

            TEAttendDetails_StartLabel As label:
                FillPortions: =1
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =350
                Size: =21
                Text: =__localizer.Localize("ANA_FILEDOC_START_DATE", LangEn)
                Width: =400
                ZIndex: =1

            TEAttendDetails_StartDatePicker As datepicker:
                DefaultDate: =AttendData.'Start Date'
                DisplayMode: =DisplayMode.Disabled
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =575
                Size: =24
                Width: =200
                ZIndex: =3

            TEAttendDetails_EndLabel As label:
                FillPortions: =1
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =350
                LineHeight: =0
                Size: =21
                Text: =__localizer.Localize("ANA_FILEDOC_END_DATE", LangEn)
                Width: =350
                ZIndex: =4

            TEAttendDetails_EndDatePicker As datepicker:
                DefaultDate: =AttendData.'End Date'
                DisplayMode: =DisplayMode.Disabled
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =575
                Size: =24
                Width: =200
                ZIndex: =5

        TEAttendDetails_Container1 As groupContainer.verticalAutoLayoutContainer:
            Height: =167
            LayoutMode: =LayoutMode.Auto
            Width: =610
            X: =15
            Y: =878
            ZIndex: =6

            Label31 As label:
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =560
                Size: =21
                Text: =__localizer.Localize("ANA_TRAINING_DETAIL_LOCATION", LangEn)
                Width: =190
                Wrap: =false
                ZIndex: =1

            Label19 As label:
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =560
                Size: =21
                Text: =AttendData.Location
                Width: =350
                ZIndex: =2

            Icon7 As icon.Flag:
                Icon: =Icon.Location
                ZIndex: =3

    TEAttendDetails_OPIIcon As icon.Help:
        Height: =44
        Icon: =Icon.Help
        OnSelect: |-
            =Navigate(
                OPIContactDetailsScreen, 
                None
            );
        Width: =34
        X: =108
        Y: =567
        ZIndex: =6

    MainHeader_6 As MainHeader:
        ZIndex: =8

